cookie:
  expiry_days: 30
  key: chetti_expense_tracker_key_2026
  name: chetti_cookie
credentials:
  usernames:
    marconigris:
      email: marconigris@gmail.com
      name: Marco
      password: $2b$12$BI/vPXAPmafCldDP2rzTE.e7Vm9i6ypnW7zBx/ESZdFZE43Px5mwm
    monigila:
      email: ''
      name: Moni
      password: $2b$12$deq7/8LSEL3W1GUSM8RvZu6JqaFfXyERAxy52IT0P/hG.a2ntLlD2
pre-authorized:
  emails: []
