cookie:
  expiry_days: 30
  key: chetti_expense_tracker_key_2026
  name: chetti_cookie
credentials:
  usernames:
    marconigris:
      email: ''
      name: Marco
      password: $2b$12$kErWvW7W7Fa/CSTDQ/yDIeBQsGYva.WnXXkfQcBv0LsijBlcucC7y
pre-authorized:
  emails: []
