cookie:
  expiry_days: 30
  key: chetti_expense_tracker_key_2026
  name: chetti_cookie
credentials:
  usernames:
    monigila:
      email: ''
      name: Moni
      password: $2b$12$5/nlSe3BHU.bEeAOa6h5PuNLevwfzYxovR3lEBkNZagp6ftDzlM4.
pre-authorized:
  emails: []
